import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession, signIn, signOut, session } from "next-auth/client";

import styles from "../styles/Home.module.css";
import Header from "../components/layouts/Header";
import { Typography } from "@mui/material";
import { useRouter } from "next/dist/client/router";
import axios from "axios";

const operations = ["build", "test", "deploy"];
const Home: NextPage = () => {
  const [session, authenticated] = useSession();
  const router = useRouter();
  const [opereation, setOperation] = React.useState<string>("");

  console.log(authenticated, session);
  React.useEffect(() => {
    let count = 0;
    setInterval(() => {
      setOperation(operations[count++ % 3]);
    }, 50000);
    if (!authenticated) {
      router.push("/api/auth/signin");
    }
    (async function () {
      const { data } = await axios.get("/api/getAuthenticatedUser", {
        withCredentials: true,
      });
      console.log(data);
    })();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <img
          src={session?.user?.image || "/"}
          alt="profile"
          style={{ width: 50, height: 50 }}
        />
        <span style={{ display: "flex", flexDirection: "row" }}>
          <Typography variant="h1" style={{ marginRight: 50 }}>
            The best CI/CD to
          </Typography>
          <Typography variant="h2" style={{ fontWeight: "bold" }}>
            {opereation}
          </Typography>
        </span>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
